export const EVENT_TYPES = {
    CURSOR:'CURSOR',
    SHAPES:'SHAPES',
    ARROW:'ARROW',
    TEXT:'TEXT',
    IMAGES:'IMAGES',
    CIRCLE:'CIRCLE',
    RECTANGLE:'RECTANGLE',
    ROUNDED_RECTANGLE:'ROUNDED_RECTANGLE',
    RHOMB:'RHOMB',
    PARALLELOGRAM:'PARALLELOGRAM',
    TRASH:'TRASH',
}
